### ISSUE TITLE
trying to convert idx/sub to pgs => crash

### ISSUE THREAD

**Issue by Selur** [captainayy/BDSup2SubPlusPlus#2]
loading any idx/sub file causes the BDSup2SubPlusPlus to crash,
For some I get:
```
WARNING: Control buffer size inconsistent.
WARNING: RLE buffer size inconsistent.
WARNING: Invalid end sequence offset -> no end time
WARNING: Invisible caption due to zero alpha (not fixed due to user setting).
```
seems and it seems to crash with an index out of bounds at:
https://github.com/captainayy/BDSup2SubPlusPlus/blob/5f8c159d2fed0ae1726718121f49d30e0821f398/src/Subtitles/subpicture.h#L52

**Comment by oniiz86** [comment]
@Selur I don't seem to have this issue, I've tried to convert a couple of idx/sub files to pgs & it processes it just fine but what I did discover is that I experienced the same warning messages above when I used an .idx file created with BDSup2Sub 5.1.1 & a .sub file created with BDSup2Sub++ 1.04b, the reason is that I accidentally deleted the .sub file created with BDSup2Sub 5.1.1 so I converted from pgs to idx/sub with BDSup2Sub++ 1.04b & I was able to use the existing .idx file with the newly created .sub that works on my media players just fine but it crashes when trying to import into BDSup2Sub++ 1.04b.

**Comment by Selur** [comment]
Hmm,.. I extracted my subtitles using mencoder.
Thanks for looking into it.
